"""Snort 3 and Suricata Industrial IDS Rule Exporter for MarlinSpike passive PCAP report data."""

from typing import Any, Dict, List


def export_snort_rules(report_data: Dict[str, Any]) -> str:
    """Generate Snort 3 / Suricata passive rules from report findings and violations."""
    if not isinstance(report_data, dict):
        report_data = {}
    findings = [f for f in report_data.get("findings", []) if isinstance(f, dict)]
    purdue_violations = [v for v in report_data.get("purdue_violations", []) if isinstance(v, dict)]

    lines: List[str] = [
        "# ==========================================================",
        "# Snort 3 / Suricata Industrial IDS Rules",
        "# Passively Generated by MarlinSpike OT Security Engine",
        "# ==========================================================",
        "",
    ]

    sid = 9000001

    # Purdue violations
    for viol in purdue_violations:
        src = viol.get("src", "any")
        dst = viol.get("dst", "any")
        proto = (viol.get("protocol") or "ip").lower()
        lines.append(
            f'alert {proto} {src} any -> {dst} any '
            f'(msg:"MARLINSPIKE Purdue Model Zone Violation ({src} -> {dst})"; '
            f'classtype:bad-unknown; sid:{sid}; rev:1;)'
        )
        sid += 1

    # OT Critical / High findings
    for finding in findings:
        cat = finding.get("category", "")
        sev = finding.get("severity", "")
        nodes = finding.get("affected_nodes", [])
        src = nodes[0] if len(nodes) > 0 else "any"
        dst = nodes[1] if len(nodes) > 1 else "any"

        if cat == "PLC_MODE_SHIFT_DETECTED":
            lines.append(
                f'alert tcp {src} any -> {dst} any '
                f'(msg:"MARLINSPIKE Critical PLC Mode Change (STOP/HALT) Detected"; '
                f'classtype:policy-violation; sid:{sid}; rev:1;)'
            )
            sid += 1
        elif cat == "LATERAL_MOVEMENT_SUSPECT":
            lines.append(
                f'alert tcp {src} any -> {dst} any '
                f'(msg:"MARLINSPIKE IT Management Protocol Reaching Purdue L1/0 PLC"; '
                f'classtype:attempted-admin; sid:{sid}; rev:1;)'
            )
            sid += 1
        elif cat == "MALFORMED_INDUSTRIAL_FRAME":
            lines.append(
                f'alert ip {src} any -> {dst} any '
                f'(msg:"MARLINSPIKE Malformed Industrial Protocol Frame / Fuzzing Attempt"; '
                f'classtype:protocol-command-decode; sid:{sid}; rev:1;)'
            )
            sid += 1

    if len(lines) <= 5:
        lines.append("# No critical rule conditions triggered for this capture.")

    return "\n".join(lines) + "\n"
