"""Industrial L2 Switch ACL & Hardening Exporter for MarlinSpike passive PCAP report data."""

from typing import Any, Dict, List


def generate_switch_acl(report_data: Dict[str, Any], vendor: str = "cisco_ie") -> str:
    """Generate native industrial switch configuration commands based on passive PCAP observations.
    
    Supported vendors: 'cisco_ie', 'siemens_scalance', 'hirschmann_hios'.
    """
    if not isinstance(report_data, dict):
        report_data = {}
    nodes = [n for n in report_data.get("nodes", []) if isinstance(n, dict)]
    edges = [e for e in report_data.get("edges", []) if isinstance(e, dict)]
    purdue_violations = [v for v in report_data.get("purdue_violations", []) if isinstance(v, dict)]

    vendor = (vendor or "cisco_ie").lower()

    lines: List[str] = []

    if vendor == "siemens_scalance":
        lines.append("! ==========================================================")
        lines.append("! Siemens SCALANCE X-300 / X-400 Hardening Script")
        lines.append("! Passively Generated by MarlinSpike OT Security Engine")
        lines.append("! ==========================================================")
        lines.append("vlan 10 name 'Control_Zone_L1'")
        lines.append("vlan 20 name 'HMI_Zone_L2'")
        lines.append("vlan 30 name 'Enterprise_Zone_L4'")
        lines.append("!")
        for idx, node in enumerate(nodes):
            ip = node.get("ip") or "N/A"
            mac = node.get("mac") or ""
            level = node.get("purdue_level", 1)
            vlan = 10 if level <= 1 else (20 if level == 2 else 30)
            if mac:
                lines.append(f"mac-address-table static {mac} vlan {vlan} interface FastEthernet0/{idx+1}")
                lines.append(f"interface FastEthernet0/{idx+1}")
                lines.append(f"  port-security max-mac-count 1")
                lines.append(f"  description 'MarlinSpike L{level} Asset {ip}'")
                lines.append("!")

    elif vendor == "hirschmann_hios":
        lines.append("# ==========================================================")
        lines.append("# Hirschmann HiOS Industrial Switch Security Configuration")
        lines.append("# Passively Generated by MarlinSpike OT Security Engine")
        lines.append("# ==========================================================")
        lines.append("vlan create 10 name Control_Zone_L1")
        lines.append("vlan create 20 name HMI_Zone_L2")
        lines.append("vlan create 30 name Enterprise_Zone_L4")
        lines.append("")
        for idx, node in enumerate(nodes):
            mac = node.get("mac") or ""
            ip = node.get("ip") or ""
            if mac:
                lines.append(f"port security 1/{idx+1} enable")
                lines.append(f"port security 1/{idx+1} static-mac {mac}")
                lines.append(f"port comment 1/{idx+1} \"MarlinSpike Asset {ip}\"")

    else:  # cisco_ie
        lines.append("! ==========================================================")
        lines.append("! Cisco Industrial Ethernet (IE 4000/5000) Micro-Segmentation ACL")
        lines.append("! Passively Generated by MarlinSpike OT Security Engine")
        lines.append("! ==========================================================")
        lines.append("vlan 10")
        lines.append(" name Control_Zone_Level1")
        lines.append("vlan 20")
        lines.append(" name Operations_Zone_Level2")
        lines.append("!")
        lines.append("ip access-list extended OT_ZERO_TRUST_ACL")
        lines.append(" remark Block unauthorized cross-Purdue traffic")
        for viol in purdue_violations:
            src = viol.get("src", "any")
            dst = viol.get("dst", "any")
            lines.append(f" deny ip host {src} host {dst}")

        lines.append(" permit tcp any any eq 502")  # Modbus
        lines.append(" permit tcp any any eq 44818") # CIP
        lines.append(" permit tcp any any eq 102")   # S7comm
        lines.append(" permit udp any any eq 20004") # DNP3
        lines.append(" deny ip any any log")
        lines.append("!")
        for idx, node in enumerate(nodes):
            mac = node.get("mac") or ""
            ip = node.get("ip") or ""
            level = node.get("purdue_level", 1)
            lines.append(f"interface GigabitEthernet1/0/{idx+1}")
            lines.append(f" description MarlinSpike L{level} {ip}")
            lines.append(f" switchport mode access")
            lines.append(f" switchport access vlan {10 if level <= 1 else 20}")
            lines.append(f" switchport port-security")
            lines.append(f" switchport port-security maximum 1")
            if mac:
                lines.append(f" switchport port-security mac-address {mac}")
            lines.append(f" ip access-group OT_ZERO_TRUST_ACL in")
            lines.append("!")

    return "\n".join(lines) + "\n"
